name: snk
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: adrianopteodoro
          gif_out_path: animations/gh-contrib-grid-snake.gif
          svg_out_path: animations/gh-contrib-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: animations
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
