name: snk
on:
  schedule:
    - cron: "0 */6 * */1 */6"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name:  ${{ github.repository_owner }}
          outputs: |
            animations/github-snake.svg
            animations/github-snake-dark.svg?palette=github-dark
            animations/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: animations
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
