name: snk
on:
  schedule:
    - cron: "0 */6 * */1 */6"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name:  ${{ github.repository_owner }}
          outputs: |
            animations/gh-contrib-grid-snake.gif
            animations/gh-contrib-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: animations
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
